# This is a basic workflow to help you get started with Actions

name: Catching CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-with-cache:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checksout the Repository
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set up uv
        run: astral-sh/setup-uv@v5

      - name: Create virtual environment
        run: uv venv
        
      - name: Cache uv dependencies
        uses: actions/cache@v4
        id: cache-uv # Give the step an id to check its output
        with:
          path: ~/.cache/uv
          key: cache-7845754

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: prime-cache-7845754
        run: |
          if [[ "${{ steps.cache-uv.outputs.cache-hit }}" == "true" ]]; then
            echo "Cache hit! Dependencies were restored."
          else
            echo "Cache miss. Dependencies were installed and cache will be saved."
          fi
